### ISSUE TITLE
Add more descriptive error messages for WaveType parsing

### ISSUE THREAD

**Issue by EmNudge** [jmg049/wavers#10]
Currently we just get "Invalid wav type" for anything not within the 4 supported types. 
24 bit PCM is **really** popular in audio engineering contexts, making me a bit confused when none of my files were able to be parsed. I later found out its a planned feature, but it would be nice to get a more descriptive error in the meantime.

Maybe something like

```rs
impl TryFrom<(u16, u16)> for WavType {
    type Error = WaversError;

    fn try_from(value: (u16, u16)) -> Result<Self, Self::Error> {
        Ok(match value {
            (1, 16) => WavType::Pcm16,
            (1, 32) => WavType::Pcm32,
            (3, 32) => WavType::Float32,
            (3, 64) => WavType::Float64,
            (1, bits_per_sample) => {
                return Err(WaversError::InvalidType(format!(
                    "No PCM encoding for {} bits per sample",
                    bits_per_sample
                )))
            },
            (3, bits_per_sample) => {
                return Err(WaversError::InvalidType(format!(
                    "No Float encoding for {} bits per sample",
                    bits_per_sample
                )))
            },
            _ => return Err(WaversError::InvalidType("Unsupported encoding type".into())),
        })
    }
}
```

**Comment by jmg049** [comment]
That's a very fair point. I haven't been able to work on Wavers at all in recent months due to work, but I will look into this and either get a quick version of PCM_24 implemented and/or improve the error messages

**Comment by jmg049** [comment]
OK so I've added 24-bit signed integers and support for PCM 24 wav files. They are highly untested and the PCM 24 bit support is definitely experimental. I have only tested this on a handful of files, so I would really appreciate it if you could report any bugs you encounter.
[
It is available now](https://crates.io/crates/wavers)

I've also made the error message more descriptive too, just in-case.

**Comment by EmNudge** [comment]
Wow, that's incredibly fast work!

Thanks so much! I'll give it a test later today and let you know if there are any problems.

**Comment by jmg049** [comment]
When the notion hits I suppose. It wasn't bad to implement at all and I had definitely thought about and looked into it previously. I knew it would have to be a wrapper around an ``i32`` in some sense. Then, thankfully, [bytemuck](https://docs.rs/bytemuck/latest/bytemuck/) and [num_traits](https://docs.rs/num-traits/latest/num_traits/) are fantastic crates that made the whole thing pretty nice.

Again though, it really isn't thoroughly teste, I've only tested on a few test wav files.

**Comment by EmNudge** [comment]
Seems to work!

Software like [Reaper](https://www.reaper.fm/) will export 24bit PCM WAV as a default, so this is likely to help compatibility with a lot of DAW-related audio.

I tried to use `ffmpeg` to convert a 16bit PCM to 24bit PCM, but it looks like ffmpeg [forces you into the "extensible" format with no plans to change this behavior](https://trac.ffmpeg.org/ticket/4426). I built a small [CLI tool yesterday](https://github.com/EmNudge/inspect-wav) to help inspect some the header info from the CLI which helped me get my head around that part.

Anyway, supporting the extensible format would probably be a considerably larger effort. I'm going to read through [this doc](https://www.mmsp.ece.mcgill.ca/Documents/AudioFormats/WAVE/WAVE.html) to get a better understanding myself (and perhaps update my own CLI tool accordingly). Just supporting 24-bit PCM should be fine for anything that isn't from ffmpeg.

**Comment by jmg049** [comment]
I think I have seen stuff about the extensible format.  It is something I would be interested in looking into for Wavers. I'll investigate at some point soon. Ffmpeg is such an established tool that it wouldn't make sense to not support the output of it directly.

**Comment by EmNudge** [comment]
Looks like the extensible format, being mostly a wrapper, has the **actual** compression format hidden in the first 2 bytes of its GUID (the last 16 bytes of the extended fmt chunk).

In FFMPEG's case this is PCM, so we can probably expand WavRS's header formatting without updating its types since it'll still just be a PCM file.

The other difference is that all non-PCM format codes require a "fact" chunk, so it'll have another 12 bytes between the fmt and data chunk.

I've added some of this parsing to my [previously mentioned CLI tool](https://github.com/EmNudge/inspect-wav) if you want to see how I'm parsing this.

**Comment by jmg049** [comment]
Yeah it doesn't seem too bad at all. I started looking into it yesterday and might be able to spend some time on it today. I do want to make sure though to not just hastily implement it and make it more of a patch than an actual feature. 

I will look at the CLI tool, thanks for sending it on. Really appreciate the engagement with Wavers. It is really getting me back into the project and making me want to work on it more. 

I am going to open a new issue though dedicated to the implementing support for the extended format and for non-PCM format code.
