### ISSUE TITLE
Add support for extended Wav format

### ISSUE THREAD

**Issue by jmg049** [jmg049/wavers#11]
Originally, Wavers was meant to be as simple as possible, and for the first major version, this meant just the original wav format. However, it was raised in Issue #10, that established tools, such as ffmpeg, produce wav files in the extended format. 

Wavers really should be compatible with such tools as people using Wavers are likely to be using them, too. 

I have started working locally on this issue. But will publish a ``wav_extension`` branch that will track changes. I am basing the implementation around [this](https://www.mmsp.ece.mcgill.ca/Documents/AudioFormats/WAVE/WAVE.html). I am still looking for a more definitive list of the sub-formats. 

Thanks to [EmNudge](https://github.com/EmNudge) for raising the original issue and providing some great references on it.

**Comment by jmg049** [comment]
Potentially working version is now on the ``wav_extension`` branch. Need to test it with files in the extensible format still.

**Comment by EmNudge** [comment]
Tested it and it seems to work for my files! (We should probably remove the `println!()` before merging)

If it helps, here is a sample audio file: [wav_ext.zip](https://github.com/jmg049/wavers/files/14561857/wav_ext.zip)

You can generate one with 
```sh
ffmpeg -i file.wav -c:a pcm_s24le out.wav
```

**Comment by jmg049** [comment]
Amazing so. I have only tested it on a single file yesterday so thanks for testing it out. Yeah I noticed the println myself when testing and I've removed it. 

In other news I have a new cli tool for viewing wav headers now. Literally just uses wavers to read the header and print it out. I'll probably create the GitHub for it today and look into cargo install for it. It was useful when testing out these changes.

**Comment by EmNudge** [comment]
Nice! I've been developing [my own WAV inspector tool](https://github.com/EmNudge/inspect-wav) to view headers to debug wavers 😅. I've been adding other chunk formats, but there's just so many of them. Would love to see more inspection tools!

**Comment by jmg049** [comment]
I have been thinking about how to add them all day haha 

There is a good few of them alright, I was thinking of wavers supporting the ``LIST`` and ``FACT`` for the time being. Then hopefully I can do it in a way which will allow more chunks easily. Would like to publish a version that does alright for the extensible format soon.

**Comment by jmg049** [comment]
Having a good set of inspection tools would be so nice

**Comment by jmg049** [comment]
Another push to the extension branch. This time polishing off the extensible feature a bit more. Also refactoring the chunks. Details in the commit and all will be documented before merging and publishing

**Comment by jmg049** [comment]
I've merged this into main and published to crates. Hopefully all works as intended. Closing this issue. When a bug pops up I'll create a new issue.
