### ISSUE TITLE
Documentation: How are channels accessed? 

### ISSUE THREAD

**Issue by jdbosser** [jmg049/wavers#13]
Hi! 

I was wondering how the different channels are accessed. I have a wav-file containing 56 channels, and I am planning to read this sample per sample for all the channels. 

Hence, I want to (pseudo-code)
```
let mut wav: Wav<f32> = Wav::from_path("test.wav")?;
let samples = wav.read_samples(1);
```
and would have suspected to get the first sample from the 56 channels, that is, a vector or an array containing 56 elements. The result of the above is that I get one value out. 

So, I assume that I need to read 56 samples, if I want to get the values of all channels at the first time instance? Or, is it something else I need to do? 

I read in the documentation that channel iteration is a planned feature. However, if the current behavior of `read_samples` is to remain, I think we could add an additional line in the documentation on the structure of the returned samples in case of multiple channels.

**Comment by jmg049** [comment]
Hey @jdbosser 

Yeah so currently there are two ways of accessing the channels:
    1. In the base WaveRs library, samples from each channel are interleaved in the results ``&[T: AudioSample]`` slice. So let us assume we have 3 channels (for brevity compared to 56) present in some slice of samples S. S[0] is channel 1 sample 1,S[1] is channel 2 sample 1, S[2] is channel 3 sample 1, S[4] channel 1 sample 2 and so on. It's not the most pleasant way, and there is an issue or note somewhere about changing this behaviour. 
    2. Enable the ``ndarray`` feature, and you can load the samples as an N-dimensional array, specifically a 2-D array where the first dimension is the samples and the second is the channels.  See [here](https://github.com/jmg049/wavers/blob/main/src/core.rs#L349) for the channel part. So in your case the resulting array would have a shape (n_samples_per_channel, n_channels)

I agree though on making it clearer in the documentation!

**Comment by jmg049** [comment]
Ok so a new version of Wavers is up on crates.io

V1.4.0 is the iteration update. It includes two iterators for the data in a wav file; ``FrameIterator`` or ``Wav::frames()`` iterates over a frame in the wav file (the samples from all channels for a given sample point, Point 1 above), and ``ChannelIterator`` or ``Wav::channels()`` which iterates over the channels. Both are relatively untested, but not completely. I've added a few new tests for iterating over wav files with more than 1 or 2 channels and all seems fine. 

Probably could do with clearing up some documentation on it still though

**Comment by jdbosser** [comment]
That is wonderful! Thank you for your help, and your quick response. Having a frame iterator is exactly what I need for my usecase.
