### ISSUE TITLE
ndarray -> Samples?

### ISSUE THREAD

**Issue by melMass** [jmg049/wavers#14]
Hi,

Thanks for this lib.
I'm trying to operate on a wav file as ndarray and then convert back once done to write to a file.
I managed to get the first part correctly but I'm stuck now on how to write it back to a file / cast it as `Samples`.

By quickly looking at the source I didn't find anything explicit for the other way around.

Is it possible?

Thanks

**Comment by jmg049** [comment]
Good question haha. I will look at this now today and get back to you. If it's possible I'll let you know how and if it isn't I'll make it possible!

Thanks for the issue.

**Comment by jmg049** [comment]
It wasn't available but thankfully easy to implement. The commit [commit](https://github.com/jmg049/wavers/commit/bbd59bef0ccb19ddbcd4bf38918732949cbc051d). 

I will publish to crates now too. There is an example of using it in the docs. I'm just realising I forgot to update the main readme though. Let me know if any problems arise.

**Comment by melMass** [comment]
Wow awesome thanks a lot for the prompt action!

**Comment by jmg049** [comment]
> Wow awesome thanks a lot for the prompt action!

No problem at all, I love working on this stuff when I can. 

Any other feature requests/missing functionality please don't hesitate to open another issue .

**Comment by melMass** [comment]
I just realized the shape has changed! Not sure if it was referenced in docs, but to let you know it's a "breaking" change.

Thanks again

**Comment by jmg049** [comment]
Yes, the shape was changed. It was done to be in line with the shape produced by the likes of soundfile. 

It was mentioned in the commit but not elsewhere. probably should have noted it under the ndarray section.

I will update the docs when I can.
