### ISSUE TITLE
Add Support for Seeking

### ISSUE THREAD

**Issue by mfpekala** [jmg049/wavers#15]
I've noticed that internally the crate has an `advance_pos` function on `Wav`, but this function is not public.

I'm writing code that works with snippets of long `wav` files, and oftentimes the section that needs to be extracted is near the end of the file. Since the file is potentially massive I want to avoid reading the entire thing into memory, or reading a bunch of unneeded samples. Right now, looking at the public API, two ways of doing this immediately come to mind:

1. Create a `Wav` and call `read_sample(s)` until I'm at the snippet I care about
2. Create something `Box<dyn ReadSeek>` myself, seek manually, and then create a `Wav` using this reader. 

Neither of these feel great. (1) will end up doing a ton of allocs and is inefficient. (2) seems hacky, as it's basically rewriting the (part of) the logic of `advance_pos` outside the crate.

It would be nice if there were a way using the API to seek to a given sample. For example, seek to the 1 millionth sample just by seeking the underlying reader. 

Thanks for maintaining WaveRs! Not sure what contributing looks like, but I'd be happy to try and implement this if it seems useful.

**Comment by jmg049** [comment]
Hey,

This sounds like a really cool thing to add, well expose. I completely agree that the crate should have something that provides seeking to a particular timestamp or sample. 

I can probably implement it tomorrow (bank holiday) and get an update out for the crate. The functionality is there so I can't imagine it'll be more than adding a few functions and some tests. 

I'm thinking of two methods so far:
1) Seek by duration/seek to timestamp 
2) Seek to nth sample

Any suggestions/requests are welcome!

**Comment by mfpekala** [comment]
That sounds great, thanks for the quick response! Seeking to either duration or nth sample would be perfect for what I'm working on

**Comment by jmg049** [comment]
Hopefully addressed by [this commit.](https://github.com/jmg049/wavers/commit/4ded5cab3e750f587c3ffaebed46fb599a503bc5) All tests are passing anyway. Please let me know if you have any issues. The crate should be updated too on [crates.io.](https://crates.io/crates/wavers)
