### ISSUE TITLE
Docs: Unable to access `ChannelIterator`, `FrameIterator` and `WavInfo` at docs.rs

### ISSUE THREAD

**Issue by jdbosser** [jmg049/wavers#20]
Hi! 

Looking at the docs.rs, I see that there are no links, nor am I able to search for, the structs mentioned in the title of this issue.

![Screenshot from 2024-07-30 09-04-19](https://github.com/user-attachments/assets/d5a088df-9fc8-454f-aca4-1cb3ee909296)

 I have figured out that it is because the sub-modules this crate defines (in `src/lib.rs`) are not public, even though sub-modules have public functions and are well documented. Is this intentional?

I have naively opened a pr #21, that makes the sub-modules public, which solves the issue. If this is "too" public, maybe there is a middle ground that can be found?

**Comment by jmg049** [comment]
Hey, I will look at this today and get it sorted.

**Comment by jmg049** [comment]
[Merged](https://github.com/jmg049/wavers/commit/1e52e8d6766973286389128ef3622abfb7dbc236)
