### ISSUE TITLE
Incorrect RIFF Chunk Size in Header of Written WAV Files

### ISSUE THREAD

**Issue by santiago046** [jmg049/wavers#24]
I encountered an issue where the RIFF chunk size in the header of written WAV files does not match the expected value of `file_size - 8`.

**Steps to Reproduce**:
1. Create a WAV file using `wavers`.
2. Read the file size and the RIFF chunk size from the header.
3. Compare the RIFF chunk size to `file_size - 8`.

**Expected Behavior**:
The RIFF chunk size in the header should be equal to `file_size - 8`.

**Actual Behavior**:
The RIFF chunk size does not match the expected value.

**Code to Reproduce**:
```rust
use std::fs::File;
use std::io::{Read, Seek, SeekFrom};
use wavers::{write, Samples};

fn main() {
    let fp = "./wav.wav";
    let sr: i32 = 16000;
    let duration = 10;
    let mut samples: Vec<f32> = (0..sr * duration).map(|x| (x as f32 / sr as f32)).collect();
    for sample in samples.iter_mut() {
        *sample *= 440.0 * 2.0 * std::f32::consts::PI;
        *sample = sample.sin();
        *sample *= i16::MAX as f32;
    }
    let samples: Samples<f32> = Samples::from(samples.into_boxed_slice()).convert();
    assert!(write(fp, &samples, sr, 1).is_ok());

    let mut file = File::open(fp).expect("Failed to open the WAV file");

    let file_size = file.metadata().expect("Failed to get file metadata").len();
    println!("File size: {} bytes", file_size);

    file.seek(SeekFrom::Start(4)).expect("Failed to seek in the file");

    let mut riff_chunk_size_bytes = [0u8; 4];
    file.read_exact(&mut riff_chunk_size_bytes).expect("Failed to read RIFF chunk size");
    let riff_chunk_size = u32::from_le_bytes(riff_chunk_size_bytes);
    println!("RIFF chunk size: {} bytes", riff_chunk_size);

    let expected_riff_chunk_size = file_size as u32 - 8;
    assert_eq!(riff_chunk_size, expected_riff_chunk_size, "RIFF chunk size does not match expected value");
    println!("RIFF chunk size is correct.");
}
```

**Comment by jmg049** [comment]
Ok I have this mostly sorted I think. The issue stems from not including the LIST or FACT chunk when writing. Still working on a way around this mostly because of the LIST chunk. I have things working locally by removing just not including them in the size calculations. Obviously not perfect, but for now it is fine. I will continue to work on this when I can.

**Comment by jmg049** [comment]
Apologies for the big delay, but the issue should be fixed by the most recent commit. The provided code passes and I have introduced a new test in core.rs for this.
